Add udev rule to run gstreamer plugin as user.
intel/icamerasrc pull request #9
Opened 2021-07-29 07:03 UTC by sylv-io

Root privileges where required since the plugin needs RW access to `/dev//dev/ipu-psys0`.
This can be fixed by add its permissions via udev.

TODO:
* Integrate udev rule installation into autoconf

Signed-off-by: Marcello Sylvester Bauer <sylv@sylv.io>

2022-11-18 15:17 UTC, Thesola10 commented on 37-ipu6-psys.rules
> +ACTION=="add", SUBSYSTEM=="intel-ipu6-psys", MODE="0660", RUN+="/usr/bin/chgrp video '%E{DEVNAME}'"
You could use `GROUP="video"` instead of a chgrp command for improved portability.

2023-03-08 04:01 UTC, hao-yao requested changes

2023-03-08 04:01 UTC, hao-yao commented on 37-ipu6-psys.rules
> +ACTION=="add", SUBSYSTEM=="intel-ipu6-psys", MODE="0660", RUN+="/usr/bin/chgrp video '%E{DEVNAME}'"
GROUP="video" works.

2023-08-28 13:41 UTC, sylv-io commented on 37-ipu6-psys.rules
> +ACTION=="add", SUBSYSTEM=="intel-ipu6-psys", MODE="0660", RUN+="/usr/bin/chgrp video '%E{DEVNAME}'"
done :+1:

2023-09-11 13:25 UTC, Thesola10 approved these changes

2025-09-01 10:53 UTC, closed without merging